---
title: "Adam Smith"
author: "Michael Foley"
date: "11/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r message=FALSE, warning=FALSE, echo=FALSE}
library(tidyverse)
library(tidytext)
library(textstem)     # lemmatize words
#library(topicmodels)  # LDA
library(stm)          # structure topic modeling
```

```{r}
tms <- readr::read_lines(url("https://oll.libertyfund.org/titles/smith-the-theory-of-moral-sentiments-and-on-the-origins-of-languages-stewart-ed/simple"))

tms2 <- ?xml2::read_html("https://oll.libertyfund.org/titles/smith-the-theory-of-moral-sentiments-and-on-the-origins-of-languages-stewart-ed/simple")
tms_parsed <- htmlTable::htmlP
tms[1:100]
tms2 %>% xml2::html_n
help(package = "rvest")
```

```{r}
library(rvest)
tms_url <- "https://oll.libertyfund.org/titles/smith-the-theory-of-moral-sentiments-and-on-the-origins-of-languages-stewart-ed/simple"

tms_html <- read_html(tms_url)
tms_text <- html_text(tms_html)

tms_split <- str_split(tms_text, "\\n")

tms_df <- data.frame(text = tms_split %>% unlist() %>% tail(-600)) %>%
  mutate(
    part = str_extract(text, regex("^Part\\s(First|Second|Third|Fourth|Fifth|Sixth|Seventh)")),
    section = str_extract(text, regex("^SECTION\\s(IV|III|II|I)")),
    section = if_else(part %in% c("Part Third", "Part Fourth", "Part Fifth"), "N/A", section),
    chapter = str_extract(text, regex("^CHAPTER\\s(VI|V|IV|III|II|I)")),
  ) %>%
  fill(part, section, chapter, .direction = "down") %>%
  filter(!str_detect(text, regex("^Part\\s(First|Second|Third|Fourth|Fifth|Sixth|Seventh)")) &
           !str_detect(text, regex("^SECTION\\s(IV|III|II|I)")) &
           !str_detect(text, regex("^Edition:\\scurrent;\\sPage:")) &
           text != "") %>%
  select(part, section, chapter, text)

data.frame(text = tms_split %>% unlist() %>% tail(-600)) %>% filter(str_detect(text, "the end"))
```

